version: '3.7'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: host-domain.com
      PMA_USER: dbUser
      PMA_PASSWORD: XXXXXX
      PMA_PORT: 3306
    ports:
      - "8080:80"
